apiVersion: apps/v1
kind: Deployment
metadata:
    name: kuberdemo-deployment
    labels:
        app: kuberdemo
spec:
  replicas: 1
  selector:
    matchLables:
      app: kuberdemo
  template:
    metadata:
      labels:
        app: kuberdemo
    spec:
      containers:
        - name: nodeserver
          image: anshulbing/kuberdemo:latest
          ports:
            - containerPort: 3000